name: Main Branch Push

on:
  push:
    branches: ["main"]
    paths:
      - "client/**"
      - ".github/workflows/**"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/lint.yaml
